### ISSUE TITLE
I WANT TO WRITE FAQ FOR YOU

### ISSUE THREAD

**Issue by LINCOM011** [TimothyMee/steem-sport#2]
I WILL LIKE TO WRITE FAQ FOR YOUR BLOG IF POSSIBLE,I WILL BE WAITING FOR YOUR GO AHEAD, I HAVE READ WHAT YOU NEED

**Comment by Pope19** [comment]
I have already written a proposal for this, and i have been given the go ahead.
Currently am working on it.

**Comment by TimothyMee** [comment]
Hi guys. 
To be fair pope19 already got my go ahead to write the FAQ and all. 
I love that you are interested and I would love if you can still contribute in some manner

Regards.

**Comment by TimothyMee** [comment]
Hi guys. 
To be fair pope19 already got my go ahead to write the FAQ and all. 
I love that you are interested and I would love if you can still contribute in some manner

Regards.
